version: "3.8"

services:
  backend:
    image: "dimasdzz/myschool-app-fullstack:1.4.2022.3.54.34"
    ports:
    - "80:8080"
    restart: "always" #if application has an issue try bring application up by restart "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev



